<?php
/**
 * Yireo AdminPreviousNext for Magento
 *
 * @package     Yireo_AdminPreviousNext
 * @author      Yireo (http://www.yireo.com/)
 * @copyright   Copyright (c) 2014 Yireo (http://www.yireo.com/)
 * @license     Open Source License
 */

$next = $this->getNext();
?>
<?php if(!empty($next)) : ?>
<style>
    button.forward {
        color: #555;
        background: none;
    }
    button.forward span {
        background: none;
        padding: 0;
    }
    button.forward:after {
        content: "»";
        padding-left: 4px;
    }
    button.forward:hover {
        background: #888 !important;
    }
</style>
<script>
var nextHtml = '<button type="button" class="forward" '
    + 'title="<?php echo $next->getName(); ?>" '
    + 'onclick="setLocation(\'<?php echo $next->getUrl(); ?>\');">'
    + '<span><span><span><?php echo $next->getLabel(); ?></span></span></span>'
    + '</button>';
$$('p.form-buttons').each(function(buttons) {
    buttons.insert({ bottom: nextHtml });
});
</script>
<?php endif; ?>
